version: "3.9"

services:
  api:
    build: .
    container_name: ampla-b2mml-v0600
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload --log-config uvicorn_logging.json
