[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ampla-b2mml-v0600"
version = "0.1.0"
description = "Ampla to B2MML transformer V0600"
readme = "README.md"
requires-python = ">=3.12"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Utilities",
]

dependencies = [
    "fastapi",
    "uvicorn",
    "lxml",
    "pydantic",
    "python-multipart",
    "openpyxl"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "httpx"
]

[project.scripts]
b2mml = "app.cli:main"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--cov=app --cov-report=term-missing"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
